replicaCount: 1

webapp:
    image: hub.k8s.ucar.edu/ncote/cirrus-user-web:2025-11-21.20.59
    image: hub.k8s.ucar.edu/ncote/cirrus-user-web:2025-11-21.20.59
  path: /
  tls:
    fqdn: cirrus.k8s.ucar.edu
    image: hub.k8s.ucar.edu/ncote/cirrus-user-web:2025-11-21.20.59
  container: 
    image: hub.k8s.ucar.edu/ncote/cirrus-user-web:2025-11-21.20.59
    port: 5000
    memory: 1G
    cpu: 2