replicaCount: 1

webapp:
  name: cirrus-website
  group: cirrus-website
  path: /
  tls:
    fqdn: cirrus.k8s.ucar.edu
    secretName: cirrus-website-ssl
  container: 
    image: hub.k8s.ucar.edu/ncote/cirrus-user-web:2025-11-24.20.28
    port: 5000
    memory: 1G
    cpu: 2