name: CIRRUS Web CICD Pipeline

on: 
  workflow_dispatch:
  push:
    paths:
      - cirrus-apps/**
      - Dockerfile
    branches:
      - main
permissions:
  contents: write
  pull-requests: write

jobs:
  podman-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v3
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d.%H.%M')" >> $GITHUB_OUTPUT
      - name: registry login
        uses: docker/login-action@v3
        with:
          registry: hub.k8s.ucar.edu
          username: robot$ncote+cirrus-web
          password: ${{ secrets.HARBOR_ROBOT_PW  }}
      - name: Build Image
        run: |
          docker buildx build -t hub.k8s.ucar.edu/ncote/cirrus-user-web:${{ steps.date.outputs.date }} .
      - name: Push Image to Harbor
        run: docker push hub.k8s.ucar.edu/ncote/cirrus-user-web:${{ steps.date.outputs.date }}
      - name: Update Helm values.yaml
        run: |
          sed -i "/cirrus-user-web/ c\    image: hub.k8s.ucar.edu/ncote/cirrus-user-web:${{ steps.date.outputs.date }}" helm-chart/values.yaml
      - name: Push changes to GitHub
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -a -m "Update Helm chart via GH Actions"
          git push
